### ISSUE TITLE
Incorrect Data Retrieval from Raider.IO on MythicPlanner.com

### ISSUE THREAD

**Issue by DrRodon** [SamFarah/RatingCalculator#2]
**Description:**
There appears to be an issue with MythicPlanner.com incorrectly fetching and displaying Mythic+ ratings from Raider.IO. Specifically, my character, Rodon, a Blood Elf Retribution Paladin on the EU server Burning Legion, is displayed with a Mythic+ rating of 2763 on MythicPlanner.com. However, my actual rating on Raider.IO is 3277. This discrepancy has been consistently observed across multiple character profiles, indicating a potential widespread data fetching or updating issue.

**Steps to Reproduce:**
1. Get into MythicPlanner.com
2. Search for character 'Rodon' on EU Burning Legion.
3. Compare the displayed Mythic+ rating with the actual rating displayed on Raider.IO.

**Expected Result:**
The ratings on MythicPlanner.com should match those on Raider.IO.

**Actual Result:**
The ratings displayed on MythicPlanner.com are outdated or incorrect compared to those on Raider.IO.

**Additional Information:**
The issue has been verified by checking multiple characters, all showing similar discrepancies in ratings between the two sites.

![image](https://github.com/user-attachments/assets/e1219b5d-d1a1-4a60-9815-9f74fd564415)
![image](https://github.com/user-attachments/assets/49640bbb-3b0d-41de-a708-a8a5e24036e6)

**Comment by supzfly** [comment]
Same, for the last 2 days.
Says the rating for a char is, 2756, but it's actually 2,960
(for reference, it's a friends char i was checking - Juggoire - Kor'gall)

**Comment by SamFarah** [comment]
@supzfly and @DrRodon , thank you for reporting this issue.
the main cause of this issue is raider.io creating multiple instances of one season when a big update happens on wow.

the mythicplanner website was just giving the latest (default) season option. I updated the website to give the latest 5 options instead (screenshot)
![image](https://github.com/user-attachments/assets/91443798-f6c6-42ae-865d-d42379e4f699)


When the latest prepatch update was released on wow, raider.io took a snapshot of everyone rating at that moment and put it under "DF Season 4" which is what the only season option mythicplanner was providing for users.
and for the current/uptodate ratings, you have to select "DF Season 4 • With Pre Patch" option from the season select that previously was not in the list, but now it should be (screenshot below).

![image](https://github.com/user-attachments/assets/3c7a96e9-48a1-4d8b-99c4-ce28d068b322)

once you select the correct season you should be able to see your correct raider.io score

the reason I had it only show the latest default season option  (and by "default" I mean a clean season name without any "• xxxxx") is because I cannot control what raider.io do with their definition of a "season" and they tend to create many arbitrary options (as you can see) that might confuse users. But I guess its better to provide the arbitrary options rather than having inaccurate results. 

Sadly raider.io API does not provide enough data to differentiate which instance of the season is the one that has the "current/live/uptodate" io scores. So here we are... apologize for any inconvenience this caused 

Please let me know if this solves the issue for you.

**Comment by DrRodon** [comment]
Hi,

I have reviewed the issue, and the update addressing the season selection has been successfully implemented. The data retrieval from Raider.IO is now functioning correctly, and the character ratings are displayed as expected. 

Thank you very much. You did amazing work here!

Best regards,
Rodon
